name: investment-dash
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - plotly
  - dash
  - dash-bootstrap-components
  - black
  - isort
  - numpy
  - pip
  - pip:
    - dash-bootstrap-templates
