name: investment-dash
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas>=2.1.3
  - plotly>=5.18.0
  - dash>=2.14.2
  - dash-bootstrap-components>=1.5.0
  - black=24.3.0
  - isort=5.13.2
  - numpy>=1.26.2
  - pre-commit=3.7.0
  - pytest=8.1.1
  - gunicorn=21.2.0
  - pip
  - pip:
    - dash-bootstrap-templates>=1.1.1